---
geometry: margin=2cm
output: pdf_document
---
```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}

# this code will install missing packages that are required automatically
  is.installed <- function(mypkg){
    is.element(mypkg, installed.packages()[,1])
  } 

  # check if package "hydroGOF" is installed
  if (!is.installed("ggplot2")){
    install.packages("ggplot2", repos="http://cran.rstudio.com/")
  }
  # check if package "hydroGOF" is installed
  if (!is.installed("dplyr")){
    install.packages("dpylr", repos="http://cran.rstudio.com/")
  }
  # check if package "hydroGOF" is installed
  if (!is.installed("Cairo")){
    install.packages("Cairo", repos="http://cran.rstudio.com/")
  }
  # check if package "hydroGOF" is installed
  if (!is.installed("reshape2")){
    install.packages("reshape2", repos="http://cran.rstudio.com/")
  }
  # check if package "hydroGOF" is installed
  if (!is.installed("knitr")){
    install.packages("knitr", repos="http://cran.rstudio.com/")
  }
  # check if package "hydroGOF" is installed
  if (!is.installed("grid")){
    install.packages("grid", repos="http://cran.rstudio.com/")
  }
  # check if package "hydroGOF" is installed
  if (!is.installed("plyr")){
    install.packages("plyr", repos="http://cran.rstudio.com/")
  }

library("plyr")
library("reshape2")
library("dplyr")
library("Cairo")
library("ggplot2")
library("knitr")
# Grid allows use of units in the plot. eg. margin adjust by cm
library("grid")
#library("xtable")

setwd("C:/Users/Admin/Documents/Coursera Classes/dmfstats/")
#setwd("C:/Users/sasmith11/Documents/R Projects/dmfstats/dmfstats")

# currently, this is hard coded as atlantic bonito. The final version will read a csv of all species, and subset from there
dat <- read.table("atlanticbonito.txt", sep="", header=FALSE)

# Add R sensitive titles to the variables
names(dat) <- c("Year", "Harvest_Number", "PSE_1", "Harvest_Pounds", "PSE_2", "Mean_Length", "Mean_Weight", "PSE_3", "Released_Number", "PSE")
# recreate year as a factor
dat$Year <- as.factor(dat$Year)

# This adjust the scales of the plot based on which variable is uncommented
# GGPLOT doesnt allow multiple y scales on the same time series
#dat$Harvest_Number <- as.numeric(dat$Harvest_Number)
#dat$Released_Number <- as.numeric(dat$Released_Number)
#dat$Harvest_Number <- dat$Harvest_Number / 10
#dat$Released_Number <- dat$Released_Number / 10
dat$Harvest_Pounds <- as.numeric(dat$Harvest_Pounds)
dat$Harvest_Pounds <- dat$Harvest_Pounds / 10^2


# Select just the columns we plan on plotting
temptidy <- select(dat, Year, Harvest_Number, Harvest_Pounds, Released_Number)
# convert the dataframe to long format (ggplot prefered)
tidyDat <- melt(temptidy, id="Year")
# reassign tidyDat$value as integer. First you must replace the comma e.g. 9,234 = 9234
tidyDat$value <- as.numeric(gsub(",","",tidyDat$value))

```
``` {r scatterplot, echo=FALSE, fig.width=8, fig.height=4, results='hide'}
#png('AtlanticBonito2.png', height=480, width=700)
# The Cairo library produces nice, smooth graphics
Cairo(600, 300, file="./Dots.png", type="png", bg="transparent")


# group = variable must be included to connect points
# This will inform geom_line() that all your points belong to one level and they should be connected.
plot3 <- ggplot(data=tidyDat,aes(x=Year, y=value, colour=variable, group=variable)) +
        geom_line() +
        # This adds the points by variable
        geom_point(aes(x=Year, y=value, colour=variable, group=variable, shape=variable)) +         
        # this sets the points shape manually
        scale_shape_manual(values=c(18,17,15)) +
        # this sets the line colors manually
        scale_colour_manual(values=c("grey", "blue","black")) +
        # This removes the background 
        theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
             panel.background = element_blank(), axis.line = element_line(colour = "black")) +       
        # this sets the line types manually
        scale_linetype_manual(values=c("solid","dotted", "solid")) + # Change linetypes
        # This turns off the tittle in the legend
        theme(legend.title=element_blank()) +
        # Move the legend to the correct position
        theme(legend.justification=c(0,1), legend.position=c(0.1,1)) +
        
        # Adjust the axis labels to be farther away from the axes
        theme(axis.title.x=element_text(vjust=-2)) +
        theme(axis.title.y=element_text(angle=90, vjust=2)) +
        theme(plot.title=element_text(size=15, vjust=3)) +
        theme(plot.margin = unit(c(0.5,0.5,0.5,0.5), "cm")) +
        theme(legend.key=element_rect(fill="transparent")) +                   
        # This turns the x-labels 45 degrees
        theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1)) +
        labs(x="Year", y="Number")         
print(plot3)
dev.off()
```
Figure 9. Atlantic bonito recreational catch in North Carolina by year.    
  
Table 37. Atlantic bonito recerational catch in North Carolina by year.
```{r, echo=FALSE, results='asis', warning=FALSE}
library(knitr)
names(dat) <- c("Year", "Harvest Num", "PSE", "Harvest lbs", "PSE", "Mean Length", "Mean Weight", "PSE", "Released Num", "PSE")
kable(dat, format = "markdown", caption="Table 37. Atlantic bonito recreational catch in North Carolina by year")
#library("pander")
#pandoc.table(dat)
```

```{r, echo=FALSE}

states <- read.csv("states.csv", header=TRUE, sep=",", na.strings="-")
stateAbbr <- read.csv("stateAbbr.csv", header=TRUE, sep=",")

# Add R sensitive titles to the variables
names(states) <- c("State", "Harvest_Number", "PSE_1", "Harvest_Pounds", "PSE_2", "Released_Number", "PSE_3", "Mean_Length", "Mean_Weight")
# recreate states as a factor
states$State <- as.factor(states$State)


# Convert mergedstates df to long form
# Select just the columns we plan on plotting
tempstates <- select(states, State, Harvest_Number, Harvest_Pounds, Released_Number)
# convert Harvest_Pounds to H_P/10^2 (REMOVE THIS WHEN WE FIGURE OUT HOW TO PLOT TWO GRAPHS ON ONE PLOT)
tempstates$Harvest_Pounds <- tempstates$Harvest_Pounds / 10^2

# convert the dataframe to long format (ggplot prefered)
tidyStates <- melt(tempstates, id="State")
# reassign tidyDat$value as integer. First you must replace the comma e.g. 9,234 = 9234
tidyStates$value <- as.numeric(gsub(",","",tidyStates$value))

# join both data sets to supplement states names with states abbreviations
mergedStates <- join(tidyStates, stateAbbr, by = "State")
# Remove the states names variable for plotting. (we plot just the abbreviations)
mergedStates <- mergedStates[,2:4]
# Rename the df so abbreviation becomes state
names(mergedStates) <- c("variable", "value", "State")
```

```{r, barrplot, echo=FALSE, fig.width=8, fig.height=4, results='hide', warning=FALSE}
#png('AtlanticBonito2.png', height=480, width=700)
# The Cairo library produces nice, smooth graphics
Cairo(600, 300, file="./bar.png", type="png", bg="transparent")
plot <- ggplot(mergedStates, aes(State, value, fill=variable)) +
        geom_bar(stat="identity",position=position_dodge(), colour="black") + # When the data contains y values in a column, use stat="identity"        
        scale_fill_manual(values=c("steelblue4", "black", "yellow2")) +
        theme_bw() + # sets theme to black and white. Although, there is a lot of grey in this? Wtf is that all about?        
        labs(x="State", y="Number") 
print(plot)
dev.off()
```
Figure 10. Atlantic bonito recreational catch by state, 2013.

Table 38. Atlantic bonito recreational catch by state, 2013.
```{r, echo=FALSE, results='asis', warning=FALSE}
names(states) <- c("State", "Harvest Num", "PSE", "Harvest lbs", "PSE", "Released Num", "PSE", "Mean Length", "Mean Weight")
kable(states, format = "markdown", caption="Table 38. Atlantic bonito recreational catch by state, 2013.")
#library("pander")
#pandoc.table(dat)
```
